#!/usr/bin/env bash
# =============================================================================
# Step 3: Create Secrets in AWS Secrets Manager
# =============================================================================
# Stores your API keys and database credentials securely in AWS.
# Usage: ./infra/aws/scripts/03-create-secrets.sh <test|prod>
# =============================================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh" "${1:-test}"

print_status "Creating Secrets for '$ENVIRONMENT' environment"

# ---------------------------------------------------------------------------
# Check for required values
# ---------------------------------------------------------------------------
if [[ -z "${MONGO_URL:-}" ]]; then
    echo ""
    echo "  You need to provide your secret values."
    echo "  Set them as environment variables before running this script:"
    echo ""
    echo "    export MONGO_URL='mongodb+srv://user:pass@cluster.mongodb.net/...'"
    echo "    export GOOGLE_API_KEY='AIza...'"
    echo ""
    echo "  Then re-run this script."
    echo ""
    read -rp "  Or enter your MongoDB connection string now: " MONGO_URL
fi

if [[ -z "${GOOGLE_API_KEY:-}" ]]; then
    read -rp "  Enter your Google Gemini API key: " GOOGLE_API_KEY
fi

DB_NAME="${DB_NAME:-shoreexplorer}"

# ---------------------------------------------------------------------------
# Create or update the secret
# ---------------------------------------------------------------------------
SECRET_VALUE=$(cat <<EOF
{
    "MONGO_URL": "$MONGO_URL",
    "GOOGLE_API_KEY": "$GOOGLE_API_KEY",
    "DB_NAME": "$DB_NAME"
}
EOF
)

if resource_exists "secret" "$SECRET_NAME"; then
    aws secretsmanager update-secret \
        --secret-id "$SECRET_NAME" \
        --secret-string "$SECRET_VALUE" \
        --region "$AWS_REGION" \
        --output text >/dev/null
    print_success "Updated existing secret: $SECRET_NAME"
else
    aws secretsmanager create-secret \
        --name "$SECRET_NAME" \
        --description "ShoreExplorer $ENVIRONMENT environment secrets" \
        --secret-string "$SECRET_VALUE" \
        --tags Key=Project,Value="$TAG_PROJECT" Key=Environment,Value="$TAG_ENVIRONMENT" \
        --region "$AWS_REGION" \
        --output text >/dev/null
    print_success "Created secret: $SECRET_NAME"
fi

# ---------------------------------------------------------------------------
# Get the secret ARN for later use
# ---------------------------------------------------------------------------
SECRET_ARN=$(aws secretsmanager describe-secret \
    --secret-id "$SECRET_NAME" \
    --query "ARN" --output text --region "$AWS_REGION")

# Save for other scripts
OUTPUT_FILE="$SCRIPT_DIR/.secrets-outputs-${ENVIRONMENT}.env"
cat > "$OUTPUT_FILE" <<EOF
# Secrets outputs for $ENVIRONMENT - generated by 03-create-secrets.sh
SECRET_NAME=$SECRET_NAME
SECRET_ARN=$SECRET_ARN
EOF

print_success "Secret ARN saved to $OUTPUT_FILE"

echo ""
echo "  Secret: $SECRET_NAME"
echo "  ARN:    $SECRET_ARN"
echo ""
echo "  To update secrets later:"
echo "    aws secretsmanager update-secret --secret-id $SECRET_NAME \\"
echo "      --secret-string '{\"MONGO_URL\":\"...\",\"GOOGLE_API_KEY\":\"...\",\"DB_NAME\":\"shoreexplorer\"}'"
echo ""
