#!/usr/bin/env bash
# =============================================================================
# Step 3: Create Secrets in AWS Secrets Manager
# =============================================================================
# Stores your API keys and database credentials securely in AWS.
# Usage: ./infra/aws/scripts/03-create-secrets.sh <test|prod>
# =============================================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh" "${1:-test}"

print_status "Creating Secrets for '$ENVIRONMENT' environment"

# ---------------------------------------------------------------------------
# Check for required values
# ---------------------------------------------------------------------------
echo ""
echo "  DynamoDB Configuration (handled via environment variables in task definition):"
echo "    - Table: myapp-${ENVIRONMENT}"
echo "    - Region: ${AWS_REGION}"
echo ""
echo "  You need to provide your Groq API key for AI plan generation."
echo "  Set it as an environment variable before running this script:"
echo ""
echo "    export GROQ_API_KEY='gsk_...'"
echo ""

if [[ -z "${GROQ_API_KEY:-}" ]]; then
    read -rp "  Enter your Groq API key: " GROQ_API_KEY
fi

# ---------------------------------------------------------------------------
# Create or update the secret
# ---------------------------------------------------------------------------
SECRET_VALUE=$(cat <<EOF
{
    "GROQ_API_KEY": "$GROQ_API_KEY"
}
EOF
)

if resource_exists "secret" "$SECRET_NAME"; then
    aws secretsmanager update-secret \
        --secret-id "$SECRET_NAME" \
        --secret-string "$SECRET_VALUE" \
        --region "$AWS_REGION" \
        --output text >/dev/null
    print_success "Updated existing secret: $SECRET_NAME"
else
    aws secretsmanager create-secret \
        --name "$SECRET_NAME" \
        --description "My App $ENVIRONMENT environment secrets" \
        --secret-string "$SECRET_VALUE" \
        --tags Key=Project,Value="$TAG_PROJECT" Key=Environment,Value="$TAG_ENVIRONMENT" \
        --region "$AWS_REGION" \
        --output text >/dev/null
    print_success "Created secret: $SECRET_NAME"
fi

# ---------------------------------------------------------------------------
# Get the secret ARN for later use
# ---------------------------------------------------------------------------
SECRET_ARN=$(aws secretsmanager describe-secret \
    --secret-id "$SECRET_NAME" \
    --query "ARN" --output text --region "$AWS_REGION")

# Save for other scripts
OUTPUT_FILE="$SCRIPT_DIR/.secrets-outputs-${ENVIRONMENT}.env"
cat > "$OUTPUT_FILE" <<EOF
# Secrets outputs for $ENVIRONMENT - generated by 03-create-secrets.sh
SECRET_NAME=$SECRET_NAME
SECRET_ARN=$SECRET_ARN
EOF

print_success "Secret ARN saved to $OUTPUT_FILE"

echo ""
echo "  Secret: $SECRET_NAME"
echo "  ARN:    $SECRET_ARN"
echo ""
echo "  DynamoDB table will be created separately using create-dynamodb-tables.sh"
echo ""
echo "  To update the Groq API key later:"
echo "    aws secretsmanager update-secret --secret-id $SECRET_NAME \\"
echo "      --secret-string '{\"GROQ_API_KEY\":\"gsk_...\"}'"
echo ""
