#!/usr/bin/env bash
# =============================================================================
# Step 4: Create IAM Roles for ECS
# =============================================================================
# Creates the permissions that ECS needs to pull images and read secrets.
# Usage: ./infra/aws/scripts/04-create-iam-roles.sh <test|prod>
# =============================================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh" "${1:-test}"

print_status "Creating IAM Roles for '$ENVIRONMENT' environment"

ACCOUNT_ID=$(get_account_id)

# Load secrets output
SECRETS_FILE="$SCRIPT_DIR/.secrets-outputs-${ENVIRONMENT}.env"
if [[ -f "$SECRETS_FILE" ]]; then
    source "$SECRETS_FILE"
else
    echo "  ⚠️  Secrets not yet created. Run 03-create-secrets.sh first."
    SECRET_ARN="arn:aws:secretsmanager:${AWS_REGION}:${ACCOUNT_ID}:secret:${SECRET_NAME}-*"
fi

# ---------------------------------------------------------------------------
# ECS Task Execution Role (pulls images, reads secrets, writes logs)
# ---------------------------------------------------------------------------
TRUST_POLICY='{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}'

if resource_exists "iam-role" "$ECS_TASK_EXECUTION_ROLE"; then
    print_skip "IAM Role: $ECS_TASK_EXECUTION_ROLE"
else
    aws iam create-role \
        --role-name "$ECS_TASK_EXECUTION_ROLE" \
        --assume-role-policy-document "$TRUST_POLICY" \
        --tags Key=Project,Value="$TAG_PROJECT" Key=Environment,Value="$TAG_ENVIRONMENT" \
        --output text >/dev/null

    # Attach the standard ECS execution policy
    aws iam attach-role-policy \
        --role-name "$ECS_TASK_EXECUTION_ROLE" \
        --policy-arn "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

    print_success "Created IAM Role: $ECS_TASK_EXECUTION_ROLE"
fi

# Create inline policy for Secrets Manager access
SECRETS_POLICY=$(cat <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue"
            ],
            "Resource": [
                "arn:aws:secretsmanager:${AWS_REGION}:${ACCOUNT_ID}:secret:${SECRET_NAME}*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:CreateLogGroup"
            ],
            "Resource": "arn:aws:logs:${AWS_REGION}:${ACCOUNT_ID}:*"
        }
    ]
}
EOF
)

aws iam put-role-policy \
    --role-name "$ECS_TASK_EXECUTION_ROLE" \
    --policy-name "${APP_NAME}-secrets-and-logs" \
    --policy-document "$SECRETS_POLICY" \
    --output text &>/dev/null 2>&1 || true

print_success "Attached Secrets Manager + CloudWatch policies"

# ---------------------------------------------------------------------------
# ECS Task Role (for the container application itself — if it needs AWS)
# ---------------------------------------------------------------------------
if resource_exists "iam-role" "$ECS_TASK_ROLE"; then
    print_skip "IAM Role: $ECS_TASK_ROLE"
else
    aws iam create-role \
        --role-name "$ECS_TASK_ROLE" \
        --assume-role-policy-document "$TRUST_POLICY" \
        --tags Key=Project,Value="$TAG_PROJECT" Key=Environment,Value="$TAG_ENVIRONMENT" \
        --output text >/dev/null

    print_success "Created IAM Role: $ECS_TASK_ROLE"
fi

# ---------------------------------------------------------------------------
# Save outputs
# ---------------------------------------------------------------------------
EXEC_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${ECS_TASK_EXECUTION_ROLE}"
TASK_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${ECS_TASK_ROLE}"

OUTPUT_FILE="$SCRIPT_DIR/.iam-outputs-${ENVIRONMENT}.env"
cat > "$OUTPUT_FILE" <<EOF
# IAM outputs for $ENVIRONMENT - generated by 04-create-iam-roles.sh
ECS_TASK_EXECUTION_ROLE_ARN=$EXEC_ROLE_ARN
ECS_TASK_ROLE_ARN=$TASK_ROLE_ARN
EOF

print_success "IAM outputs saved to $OUTPUT_FILE"

echo ""
echo "  Execution Role: $ECS_TASK_EXECUTION_ROLE"
echo "  Task Role:      $ECS_TASK_ROLE"
echo ""
