#!/usr/bin/env bash
# =============================================================================
# Step 5: Create ECS Cluster and CloudWatch Log Groups
# =============================================================================
# Creates the ECS cluster (the container hosting platform) and log groups.
# Usage: ./infra/aws/scripts/05-create-ecs-cluster.sh <test|prod>
# =============================================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh" "${1:-test}"

print_status "Creating ECS Cluster for '$ENVIRONMENT' environment"

# ---------------------------------------------------------------------------
# Create CloudWatch Log Groups
# ---------------------------------------------------------------------------
for LOG_GROUP in "$BACKEND_LOG_GROUP" "$FRONTEND_LOG_GROUP"; do
    if resource_exists "log-group" "$LOG_GROUP"; then
        print_skip "Log group: $LOG_GROUP"
    else
        aws logs create-log-group \
            --log-group-name "$LOG_GROUP" \
            --region "$AWS_REGION" \
            --tags Project="$TAG_PROJECT",Environment="$TAG_ENVIRONMENT"
        print_success "Created log group: $LOG_GROUP"
    fi

    # Set retention to 14 days (saves costs)
    aws logs put-retention-policy \
        --log-group-name "$LOG_GROUP" \
        --retention-in-days 14 \
        --region "$AWS_REGION" 2>/dev/null || true
done

print_success "Log retention set to 14 days"

# ---------------------------------------------------------------------------
# Create ECS Cluster
# ---------------------------------------------------------------------------
if resource_exists "ecs-cluster" "$ECS_CLUSTER_NAME"; then
    print_skip "ECS Cluster: $ECS_CLUSTER_NAME"
else
    aws ecs create-cluster \
        --cluster-name "$ECS_CLUSTER_NAME" \
        --capacity-providers FARGATE \
        --default-capacity-provider-strategy capacityProvider=FARGATE,weight=1 \
        --settings '[{"name":"containerInsights","value":"disabled"}]' \
        --tags key=Project,value="$TAG_PROJECT" key=Environment,value="$TAG_ENVIRONMENT" \
        --region "$AWS_REGION" \
        --output text >/dev/null
    print_success "Created ECS Cluster: $ECS_CLUSTER_NAME"
fi

# ---------------------------------------------------------------------------
# Save outputs
# ---------------------------------------------------------------------------
OUTPUT_FILE="$SCRIPT_DIR/.ecs-outputs-${ENVIRONMENT}.env"
cat > "$OUTPUT_FILE" <<EOF
# ECS outputs for $ENVIRONMENT - generated by 05-create-ecs-cluster.sh
ECS_CLUSTER_NAME=$ECS_CLUSTER_NAME
BACKEND_LOG_GROUP=$BACKEND_LOG_GROUP
FRONTEND_LOG_GROUP=$FRONTEND_LOG_GROUP
EOF

print_success "ECS outputs saved to $OUTPUT_FILE"

echo ""
echo "  Cluster: $ECS_CLUSTER_NAME"
echo "  Logs:    $BACKEND_LOG_GROUP"
echo "           $FRONTEND_LOG_GROUP"
echo ""
